config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patient_cards
  resources :patients
  resources :doctors
  resources :specializations
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "root#index"
end

app/models/patient_card.rb
class PatientCard < ApplicationRecord
  belongs_to :department
  belongs_to :doctor
  belongs_to :patient
end

app/controllers/patient_cards_controller.rb
class PatientCardsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_patient_card, only: %i[ show edit update destroy ]

  # GET /patient_cards or /patient_cards.json
  def index
    patient_cards_query = PatientCardsQuery.new
    @patient_cards = patient_cards_query.search(params[:query]).sort(params[:sort_field], params[:sort_direction]).result.paginate(page: params[:page], per_page: 10)
  end


  # GET /patient_cards/1 or /patient_cards/1.json
  def show
  end

  # GET /patient_cards/new
  def new
    @patient_card = PatientCard.new
  end

  # GET /patient_cards/1/edit
  def edit
  end

  # POST /patient_cards or /patient_cards.json
  def create
    @patient_card = PatientCard.new(patient_card_params)

    respond_to do |format|
      if @patient_card.save
        format.html { redirect_to patient_card_url(@patient_card), notice: "Patient card was successfully created." }
        format.json { render :show, status: :created, location: @patient_card }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patient_cards/1 or /patient_cards/1.json
  def update
    respond_to do |format|
      if @patient_card.update(patient_card_params)
        format.html { redirect_to patient_card_url(@patient_card), notice: "Patient card was successfully updated." }
        format.json { render :show, status: :ok, location: @patient_card }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patient_cards/1 or /patient_cards/1.json
  def destroy
    @patient_card.destroy

    respond_to do |format|
      format.html { redirect_to patient_cards_url, notice: "Patient card was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient_card
      @patient_card = PatientCard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_card_params
      params.require(:patient_card).permit(:department_id, :doctor_id, :patient_id)
    end
end

app/helpers/patient_cards_helper.rb
module PatientCardsHelper
end

app/views/patient_cards/_form.html.erb
<div class="card-body">
<%= form_with(model: patient_card, class: 'needs-validation', novalidate: true) do |form| %>
  <% if patient_card.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(patient_card.errors.count, "error") %> prohibited this patient card from being saved:</h2>

      <ul>
        <% patient_card.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
      

  <div class="form-group">
    <%= form.label :department_id, style: 'form-label' %>
    <%=  form.text_field :department_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :doctor_id, class: 'form-label' %>
    <%= form.text_field :doctor_id, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :patient_id, class: 'form-label' %>
    <%= form.text_field :patient_id, class: 'form-control' %>
  </div>

  <div class="text-center">
    <%= form.submit 'Save', class: 'btn btn-primary' %>
  </div>

  <% end %>
</div>

app/views/patient_cards/_patient_card.html.erb
<div id="<%= dom_id patient_card %>" class="card bg-light mt-3">
  <div class="card-body">
    <p class="card-text">
      <strong>Name:</strong> <%= patient_card.department_id %>
    </p>

    <p class="card-text">
      <strong>Department:</strong> <%= patient_card.doctor_id %>
    </p>

    <p class="card-text">
      <strong>Specialization:</strong> <%= patient_card.patient_id %>
    </p>
  </div>
</div>

app/views/patient_cards/edit.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="card mx-auto mt-5" style="max-width: 450px;">
    <div class="card-header bg-primary text-white">
      <h5 class="card-title text-center">Editing patient card</h5>
    </div>
    <div class="card-body">
      <p class="text-success text-center"><%= notice %></p>

      <div>
      <%= render "form", patient_card: @patient_card %>
      </div>
      <div class="text-center">
      <%= link_to "Show this patient card", @patient_card, class: 'btn btn-primary mb-2' %>
      <%= link_to "Back to patient cards", patient_cards_path, class: 'btn btn-secondary ml-2 mb-2' %>
      </div>
    </div>
  </div>
</div>

app/views/patient_cards/index.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <p class="text-success"><%= notice %></p>
      <h1>Patient cards</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-12 style_for_pages">
      <%= form_with(url: patient_cards_path, method: :get) do |form| %>
        <div class="input-group mb-3">
          <%= form.text_field :query, placeholder: 'Search patient cards', class: 'form-control' %>
          <div class="input-group-append">
            <%= form.submit 'Search', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 style_for_pages" id="patient_cards">
    <table class="table table-striped">
    <thead>
      <tr>
        <th>Department</th>
        <th>Doctor</th>
        <th>Patient</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @patient_cards.each do |patient_card| %>
        
        <tr>
          <td><%= patient_card.department.name %></td>
          <td><%= patient_card.doctor_id %></td>
          <td><%= patient_card.patient_id %></td>
          <td>
            <%= link_to "Show", patient_card, class: 'btn btn-info' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
    </div>
    
  </div>

<div class="row">
  <div class="col-12 text-center">
    <nav aria-label="Pagination">
      <ul class="pagination justify-content-center">
        <% if @patient_cards.previous_page %>
          <li class="page-item">
            <%= link_to '← Previous', patient_cards_path(page: @patient_cards.previous_page), class: 'page-link' %>
          </li>
        <% else %>
          <li class="page-item disabled">
            <span class="page-link">← Previous</span>
          </li>
        <% end %>

        <% visible_pages = 5 %>
        <% half_visible_pages = (visible_pages / 2).floor %>
        <% start_page = [@patient_cards.current_page - half_visible_pages, 1].max %>
        <% end_page = [start_page + visible_pages - 1, @patient_cards.total_pages].min %>


        <% if start_page > 1 %>
          <li class="page-item">
            <%= link_to '1', patient_cards_path(page: 1), class: 'page-link' %>
          </li>
          <% if start_page > 2 %>
            <li class="page-item disabled">
              <span class="page-link">...</span>
            </li>
          <% end %>
        <% end %>

        <% (start_page..end_page).each do |page| %>
          <% if @patient_cards.current_page == page %>
            <li class="page-item active">
              <span class="page-link"><%= page %></span>
            </li>
          <% else %>
            <li class="page-item">
              <%= link_to page, patient_cards_path(page: page), class: 'page-link' %>
            </li>
          <% end %>
        <% end %>

        <% if end_page < @patient_cards.total_pages %>
          <% if end_page < @patient_cards.total_pages - 1 %>
            <li class="page-item disabled">
              <span class="page-link">...</span>
            </li>
          <% end %>
          <li class="page-item">
            <%= link_to @patient_cards.total_pages, patient_cards_path(page: @patient_cards.total_pages), class: 'page-link' %>
          </li>
        <% end %>

        <% if @patient_cards.next_page %>
          <li class="page-item">
            <%= link_to 'Next →', patient_cards_path(page: @patient_cards.next_page), class: 'page-link' %>
          </li>
        <% else %>
          <li class="page-item disabled">
            <span class="page-link">Next →</span>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>


  <div class="row mt-2">
    <div class="col-12 text-center">
      <p>Sort by:</p>
      <p>
        <%= link_to 'Created at (asc)', { sort_field: 'created_at', sort_direction: 'asc' }, class: 'btn btn-outline-primary mr-2' %>
        <%= link_to 'Created at (desc)', { sort_field: 'created_at', sort_direction: 'desc' }, class: 'btn btn-outline-primary mr-2' %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-12 text-center">
      <p>
        <%= link_to 'New Patient Card', new_patient_card_path, class: 'btn btn-primary' %>
      </p>
    </div>
  </div>
</div>

app/views/patient_cards/new.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="card mx-auto mt-5" style="max-width: 400px;">
    <div class="card-header">
      <h5 class="card-title text-center">New patient card</h5>
    </div>
    <%= render "form", patient_card: @patient_card %>
    <div>
    <div class="card-footer text-center">
    <%= link_to "Back to patient cards", patient_cards_path, class: 'btn btn-secondary' %>
  </div>
  </div>
  </div>
</div>

app/views/patient_cards/show.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="card mx-auto mt-5" style="max-width: 400px;">
    <div class="card-header bg-primary text-white">
      <h5 class="card-title text-center">Patient Card Information</h5>
    </div>
    <div class="card-body">
      <p class="text-success text-center"><%= notice %></p>

      <div>
      <%= render @patient_card %>
      </div>

      <div class="text-center mt-3">
      <%= link_to "Edit this patient card", edit_patient_card_path(@patient_card), class: 'btn btn-primary mb-2' %>
      <%= link_to "Back to patient cards", patient_cards_path, class: 'btn btn-secondary ml-2 mb-2' %>
      <%= button_to "Destroy this patient card", @patient_card, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger ml-2' %>
      </div>
    </div>
  </div>