config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patient_cards
  resources :patients
  resources :doctors
  resources :specializations
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "root#index"
end

app/models/specialization.rb
class Specialization < ApplicationRecord
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_specialization, only: %i[ show edit update destroy ]

  # GET /specializations or /specializations.json
  def index
    @specializations = Specialization.paginate(page: params[:page], per_page: 10)

    specializations_query = SpecializationsQuery.new
    @specializations = specializations_query.search(params[:query]).sort(params[:sort_field], params[:sort_direction]).result.paginate(page: params[:page], per_page: 10)
  end

  # GET /specializations/1 or /specializations/1.json
  def show
  end

  # GET /specializations/new
  def new
    @specialization = Specialization.new
  end

  # GET /specializations/1/edit
  def edit
  end

  # POST /specializations or /specializations.json
  def create
    @specialization = Specialization.new(specialization_params)

    respond_to do |format|
      if @specialization.save
        format.html { redirect_to specialization_url(@specialization), notice: "Specialization was successfully created." }
        format.json { render :show, status: :created, location: @specialization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specializations/1 or /specializations/1.json
  def update
    respond_to do |format|
      if @specialization.update(specialization_params)
        format.html { redirect_to specialization_url(@specialization), notice: "Specialization was successfully updated." }
        format.json { render :show, status: :ok, location: @specialization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specializations/1 or /specializations/1.json
  def destroy
    @specialization.destroy

    respond_to do |format|
      format.html { redirect_to specializations_url, notice: "Specialization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization
      @specialization = Specialization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def specialization_params
      params.require(:specialization).permit(:name)
    end
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/views/specializations/_form.html.erb
<div class="card-body">
<%= form_with(model: specialization, class: 'needs-validation', novalidate: true) do |form| %>
  <% if specialization.errors.any? %>
    <div class="alert alert-danger">
      <h2><%= pluralize(specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

      <ul>
        <% specialization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="text-center">
      <%= form.submit 'Save', class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/specializations/_specialization.html.erb
<div id="<%= dom_id specialization %>" class="card bg-light mt-3">
  <div class="card-body">
    <p class="card-text">
      <strong>Name:</strong> <%= specialization.name %>
    </p>

  </div>
</div>

app/views/specializations/edit.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="card mx-auto mt-5" style="max-width: 400px;">
    <div class="card-header bg-primary text-white">
      <h5 class="card-title text-center">Editing specialization</h5>
    </div>
    <div class="card-body">
      <p class="text-success text-center"><%= notice %></p>

      <div>
      <%= render "form", specialization: @specialization %>
      </div>
      <div class="text-center">
      <%= link_to "Show this specialization", @specialization, class: 'btn btn-primary mb-2' %>
      <%= link_to "Back to specializations", specializations_path, class: 'btn btn-secondary ml-2 mb-2' %>
      </div>
    </div>
  </div>
</div>

app/views/specializations/index.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="row">
    <div class="col-12">
      <p class="text-success"><%= notice %></p>
      <h1>Specializations</h1>
    </div>
  </div>

  <div class="row">
    <div class="col-12 style_for_pages">
      <%= form_with(url: specializations_path, method: :get) do |form| %>
        <div class="input-group mb-3">
          <%= form.text_field :query, placeholder: 'Search specialization', class: 'form-control' %>
          <div class="input-group-append">
            <%= form.submit 'Search', class: 'btn btn-primary' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-12 style_for_pages">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Specialization Name</th>
            <th>Specialization Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @specializations.each do |specialization| %>
            <tr>
            <td><%= specialization.name %></td>
            <td>
              <%= link_to "Show this specialization", specialization, class: 'btn btn-info' %>
            </td>
          </tr>
          
          <% end %>
        </tbody>
      </table>


    </div>
  </div>



  <div class="row">
  <div class="col-12 text-center">
    <nav aria-label="Pagination">
      <ul class="pagination justify-content-center">
        <% if @specializations.previous_page %>
          <li class="page-item">
            <%= link_to '← Previous', specializations_path(page: @specializations.previous_page), class: 'page-link' %>
          </li>
        <% else %>
          <li class="page-item disabled">
            <span class="page-link">← Previous</span>
          </li>
        <% end %>

        <% visible_pages = 5 %>
        <% half_visible_pages = (visible_pages / 2).floor %>
        <% start_page = [@specializations.current_page - half_visible_pages, 1].max %>
        <% end_page = [start_page + visible_pages - 1, @specializations.total_pages].min %>

        <% if start_page > 1 %>
          <li class="page-item">
            <%= link_to '1', specializations_path(page: 1), class: 'page-link' %>
          </li>
          <% if start_page > 2 %>
            <li class="page-item disabled">
              <span class="page-link">...</span>
            </li>
          <% end %>
        <% end %>

        <% (start_page..end_page).each do |page| %>
          <% if @specializations.current_page == page %>
            <li class="page-item active">
              <span class="page-link"><%= page %></span>
            </li>
          <% else %>
            <li class="page-item">
              <%= link_to page, specializations_path(page: page), class: 'page-link' %>
            </li>
          <% end %>
        <% end %>

        <% if end_page < @specializations.total_pages %>
          <% if end_page < @specializations.total_pages - 1 %>
            <li class="page-item disabled">
              <span class="page-link">...</span>
            </li>
          <% end %>
          <li class="page-item">
            <%= link_to @specializations.total_pages, specializations_path(page: @specializations.total_pages), class: 'page-link' %>
          </li>
        <% end %>

        <% if @specializations.next_page %>
          <li class="page-item">
            <%= link_to 'Next →', specializations_path(page: @specializations.next_page), class: 'page-link' %>
          </li>
        <% else %>
          <li class="page-item disabled">
            <span class="page-link">Next →</span>
          </li>
        <% end %>
      </ul>
    </nav>
  </div>
</div>


<!-- 
<div class="row">
<div class="col-12 text-center">
  <%= link_to "New specialization", new_specialization_path, class: 'btn btn-primary' %>
</div>
</div>
-->

<div class="row mt-2">
<div class="col-12">
  <div class="col-12 text-center"> Sort by:
    <p class="mt-2">
      <%= link_to 'Name (asc)', { sort_field: 'name', sort_direction: 'asc' }, class: 'btn btn-outline-primary mr-2' %>
      <%= link_to 'Name (desc)', { sort_field: 'name', sort_direction: 'desc' }, class: 'btn btn-outline-primary mr-2' %>
      <%= link_to 'Created at (asc)', { sort_field: 'created_at', sort_direction: 'asc' }, class: 'btn btn-outline-primary mr-2' %>
      <%= link_to 'Created at (desc)', { sort_field: 'created_at', sort_direction: 'desc' }, class: 'btn btn-outline-primary mr-2' %>
    </p>
  </div>
</div>
</div>

app/views/specializations/new.html.erb
<h1>New specialization</h1>

<div class="style_for_pages">
  <%= render "form", specialization: @specialization %>

  <br>

  <div>
    <%= link_to "Back to specializations", specializations_path %>
  </div>
</div>

app/views/specializations/show.html.erb
<%= render 'shared/header' %>

<div class="container">
  <div class="card mx-auto mt-5" style="max-width: 500px;">
    <div class="card-header bg-primary text-white">
      <h5 class="card-title text-center">Specialization Info</h5>
    </div>
    <div class="card-body">
      <p class="text-success text-center"><%= notice %></p>

      <div>
      <%= render @specialization %>
      </div>

      <div class="text-center mt-3">
      <%= link_to "Edit this specialization", edit_specialization_path(@specialization), class: 'btn btn-primary mb-2' %>
      <%= link_to "Back to specializations", specializations_path, class: 'btn btn-secondary ml-2 mb-2' %>
      <%= button_to "Destroy this specialization", @specialization, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger ml-2' %>
      </div>
    </div>
  </div>