config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :patient_cards
  resources :patients
  resources :doctors
  resources :specializations
  resources :departments
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "root#index"
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%= link_to 'Clinic App', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= link_to 'Doctors', doctors_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Patients', patients_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Departments', departments_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Patient Cards', patient_cards_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to 'Specialization', specializations_path, class: 'nav-link' %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item ml-3">
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'btn btn-danger' %>
          </li>
        <% else %>
          <li class="nav-item ml-3">
            <%= button_to "Sign in", new_user_session_path, class: 'btn btn-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>